#!/usr/bin/env bash

ln -s config/.zshenv ~/.zshenv

ln -s config/atuin ~/.config/atuin
ln -s config/git ~/.config/git
ln -s config/lazygit ~/.config/lazygit
ln -s config/nvim-local ~/.config/nvim-local
ln -s config/starship.toml ~/.config/starship.toml
ln -s config/zellij ~/.config/zellij
ln -s config/zsh ~/.config/zsh

. "./install-deps"
