#!/usr/bin/env bash

mkdir -p ~/.config

link() {
  rm -rf "$2"
  ln -s "$1" "$2"
}

link "$(pwd)/config/.zshenv" ~/.zshenv

link "$(pwd)/config/atuin" ~/.config/atuin
link "$(pwd)/config/git" ~/.config/git
link "$(pwd)/config/lazygit" ~/.config/lazygit
link "$(pwd)/config/nvim-local" ~/.config/nvim-local
link "$(pwd)/config/starship.toml" ~/.config/starship.toml
link "$(pwd)/config/zellij" ~/.config/zellij
link "$(pwd)/config/zsh" ~/.config/zsh
